[package]
name = "debug-actix-query-params"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8"
serde = { version = "1.0", features = ["derive"] }
serde_urlencoded = "0.7"
tokio = { version = "1", features = ["full"] }
axum = "0.7.5"
